name: validate
on:
  pull_request:
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:    
  rustfmt-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update apt
      run: sudo apt update
    - name: Install dependencies
      run: |
        sudo apt-get install libasound2-dev
    - name: Run cargo fmt
      run: cargo fmt --all -- --check
    - name: Run cargo clippy
      run: cargo clippy --all --
  macos-check:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: cargo test --all-features
  ubuntu-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update apt
      run: sudo apt update
    - name: Install dependencies
      run: |
        sudo apt-get install libasound2-dev
    - name: Test
      run: cargo test --all-features
  windows-check:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: cargo test --all-features
